---
title: "chamber_vegetation_surveys_foljemaden"
author: "RMondav"
date: "2024-11-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

wkdir <- "/Users/Rhiannon/Documents/2023/Lund_universitetet"

WLpath <- paste0(wkdir,"/Faltarbeter_grejer/water_table/WTD_Foljemaden")

fdpath <- paste0(wkdir,"/Faltarbeter_grejer/field_days")
fwkdir <- paste0(wkdir,fdpath,"/transect_vegetation_data")
chvpath <- paste0(fdpath,"/chamber_vegtn_data")
chgpath <- paste0(fdpath,"/chamber_gas_data")

projdir <- paste0(wkdir,"/Data_analyses_foljemaden")
figdir <- paste0(projdir,"/graphs")
tabledir <- paste0(projdir,"/tables")
scriptdir <- paste0(projdir,"/scripts")

```



```{r chamber vegpreprocessing}
##read in chamber vegetation data
chamber_VEG_231004 <-
  read.csv(paste0(chvpath,"/chamber_VEG_foljemaden_231004.csv"))
chamber_VEG_230621 <-
  read.csv(paste0(chvpath,"/chamber_VEG_foljemaden_230621.csv"))
#rename chamber ID columns to be consistent across all dfs
colnames(chamber_VEG_231004)[1] <- "FrameID"
colnames(chamber_VEG_230621)[1] <- "FrameID"
#remove columns that aren't needed
chamber_VEG_functyp_231004 <- chamber_VEG_231004[,-2:-7]
chamber_VEG_functyp_231004 <- chamber_VEG_functyp_231004[,-8:-9]
chamber_VEG_functyp_230621 <- chamber_VEG_230621[,-2:-7]
chamber_VEG_functyp_230621 <- chamber_VEG_functyp_230621[,-8:-9]

# categories
# chambers
veg_chamber_col_names <- 
  c("FrameID","pcnt_cvr_grasses","pcnt_cvr_sedges","pcnt_cvr_mosses",
    "pcnt_cvr_water","pcnt_cvr_herbs","pcnt_cvr_tree","pcnt_cvr_plant_litter",
    "pcnt_cvr_bare_ground")
veg_chamber_base_names <- 
  c("FrameID","grasses","sedges","mosses","water","herbs","tree",
    "plant_litter","bare_ground")
#transects
veg_transct_base_names <- 
  c("logging_residue","other_debris","bare_ground","water","lichen",
    "moss_sphagnum","moss_other","grass","deciduous_and_herbs","evergreen")
#possibe chategories to compare across the datasets
veg_compare_typ <- 
  c("bare_ground","water","gramminoid","mosses","trees_herbs")
unique_cvr_typ <-
  c("logging_residue","other_debris","plant_litter") #no recorded lichen

#siv = reeds (sedges?)
#graminoid = grass + reeds + sedges + rushes
#hallon = rasberry = deciduous herb
#carex = graminoid,	bracken/bräken/bregne	= deciduous herb, 
#potentilla = dec herb,	festuca = tussock grass, graminoid
#blueberry/blåbär = dec herb
#salix or rön = willow or rohan = dec tree
#spruce, pine = evergreen
#lingon-berry = dec herb
#maj-blomst
#birch/björk or poplar/popel	= dec tree
#fireweed/mjölke = dec herb
#


# read in and preprocess chamber vegetation surveys by date 
library(dplyr)
survey_dates = c("231004","230621")
for (sdate in survey_dates) {
  ##read in chamber vegetation data
  xt <- read.csv(paste0(chvpath,"/chamber_VEG_foljemaden_",sdate,".csv"))
  #rename chamber ID columns to be consistent across all dfs
  colnames(xt)[1] <- "FrameID"
  #remove columns that aren't needed
  xt1 <- xt[,-2:-7]
  xt <- xt1[,-8:-9]
  #add survey date as date-formatted column
  xt$survey_date <- format(as.Date(sdate, format = "%y%m%d"), "%Y-%m-%d")
  # assign sample names to column
  xt$site_code <- xt$FrameID
  # make new and unique row labels
  row.names(xt) <- (paste(xt$site_code, xt$survey_date, sep = "_"))
  xt$sample_code <- (paste(xt$site_code, xt$survey_date, sep = "_"))
  #format date column
  xt$survey_date <- as.Date(xt$survey_date, "%Y-%m-%d")
  #replace all NAs with zero
  xt <- xt %>% replace(is.na(.), 0)

  #assign df to variable name
  #build sheet name for each date
  assign(paste0("chamber_VEG_functyp_",sdate),xt)
}
rm(xt); rm(xt1)



```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
